#!/bin/bash -l
# --- Log file and error file names ---
#SBATCH -e ./job.err.%j

# Initial working directory:
#SBATCH -D ./

# Job Name:
#SBATCH -J TS

# Runtime and memory
#SBATCH --time=3:00:00
#SBATCH --mem=92g

# For parallel jobs
#SBATCH --cpus-per-task=40
#SBATCH --nodes=1
#SBATCH --ntasks=1

python ./compute_opac.py  ./config.txt 'TSO'
